version: '3'

services: 
  api-herois:
    # build: .
    image: claudiuri/api-heroes:v1
    ports: 
      - 3000:3000
    environment: 
      MONGO_URL: mongodb

    depends_on: 
      - mongodb
    links: 
      - mongodb

  mongodb:
    image: mongo:4
    ports: 
      - 27017:27017